### ISSUE TITLE
Livepeer not included in subgraphDeployments

### ISSUE THREAD

**Issue by akme** [graphprotocol/graph-network-subgraph#121]
Livepeer subgraph not included in subgraphDeployments response to network-mainnet-subgraph, but everybody indexed it as `Qmaz1R8vcv9v3gUfksqiS9JUz7K9G8S5By3JYn8kTiiP5K`

Request:
```
{
  subgraphs(first:10, where:{displayName:"Livepeer"}) {
    id
    displayName
  }
  subgraphDeployments(first:10,where:{originalName:"Livepeer"}){
    id
    originalName
  }
}
```
Response:
```
{
  "data": {
    "subgraphDeployments": [],
    "subgraphs": [
      {
        "displayName": "Livepeer",
        "id": "0xb31aa1f312595af94f184c5791dc03d6af12fbff-0"
      }
    ]
  }
}
```

**Comment by abarmat** [comment]
The reason for that is that a subgraph deployment was created for Livepeer but a name was not created in the GNS.

**Comment by akme** [comment]
What's the best way to deal with such behavior? Should we get the subgraph current version and find its deployment by querying the exact subgraphVersion? Doesn't it look very complicated way, because of empty GNS?
Maybe there is any way to make it mandatory for deployment to require all settings configured?

**Comment by abarmat** [comment]
It all depends on what is the main purpose of the query. If it is to see the subgraphs worth indexers you should query for: 

```
  subgraphDeployments {
    id
   signalledTokens
  }
```

The network will give indexing rewards to any subgraph deployment with tokens signalled, it doesn't need to be in the GNS, that part is only for managing versions and showing extra information.

**Comment by juanmardefago** [comment]
@akme expanding on @abarmat's answer, the reason you can't find the `Livepeer` subgraph on your query is because you are searching it by it's `originalName`. Since that subgraph hasn't been configured with a name through the GNS contract, the actual `SubgraphDeployment` entity has no data about the name, but the `SubgraphDeployment` entity for that subgraph actually exists, if you query for all subgraph deployments, or query directly by it's ID.

**Comment by akme** [comment]
It just has wrong name:
query
```
{
  subgraphs(first:2, where:{id:"0xb31aa1f312595af94f184c5791dc03d6af12fbff-0"}) {
    id
    displayName
    currentVersion {
      id
    }
  }
  subgraphVersions(first:2, where:{subgraph:"0xb31aa1f312595af94f184c5791dc03d6af12fbff-0"}){
    id
    subgraph {
      id
      displayName
    }
    subgraphDeployment {
      id
    }
  }
  subgraphDeployment(id:"0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e66502ab0076b7218f98a"){
    id
    originalName
  }
  subgraphs(first:10, where:{displayName:"Livepeer"}){
    id
  }
}
```
response
```
{
  "data": {
    "subgraphDeployment": {
      "id": "0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e66502ab0076b7218f98a",
      "originalName": "PoolTogether"
    },
    "subgraphVersions": [
      {
        "id": "0xb31aa1f312595af94f184c5791dc03d6af12fbff-0-0.0",
        "subgraph": {
          "displayName": "Livepeer",
          "id": "0xb31aa1f312595af94f184c5791dc03d6af12fbff-0"
        },
        "subgraphDeployment": {
          "id": "0xbbde25a2c85f55b53b7698b9476610c3d1202d88870e66502ab0076b7218f98a"
        }
      }
    ],
    "subgraphs": [
      {
        "currentVersion": {
          "id": "0xb31aa1f312595af94f184c5791dc03d6af12fbff-0-0.0"
        },
        "displayName": "Livepeer",
        "id": "0xb31aa1f312595af94f184c5791dc03d6af12fbff-0"
      }
    ]
  }
}
```
and also same with Enzyme subgraph, why do they have PoolTogether original name in subgraphDeployments?
if empty then PoolTogether?)

**Comment by juanmardefago** [comment]
@akme not sure why it's like this, but this is something handled in the GNS part of the system, and doesn't affect reward distribution or any other metric that indexers should be worried about.

It might be possible to rectify the naming afterwards, but I'm not 100% sure on how it should be done.

Either way, it's not an issue with the subgraph code (at least apparently), but rather an issue with the initial deployment through GNS

@abarmat should I close this issue and create another one somewhere to rectify the metadata for the deployments?

**Comment by abarmat** [comment]
@davekaj can you look at this one? are these the subgraphs deployed before the migration?

**Comment by davekaj** [comment]
Yeah , what happened here is we had someone who started deploying subgraphs on their own. And they lazily were copying the IPFS hash for the Pool together subgraph.

so they really make the names ugly in the subgraph. because it is open and permissionless, this is allowed. 

One day we could make a system that filters it a bit better, but that is for the future. for now we should leave as is. 

I will close this - the summary to read here is that anyone can publish any name and the subgraph will accept it. Thank you for pointing this out :) @akme
